### ISSUE TITLE
Not all Fn-keys work - Thinkpad E14 Gen2 Intel

### ISSUE THREAD

**Issue by Barabazs** [rodmaureirac/thinkpad-e14-linux#10]
Hi. I just wanted to let you know that F9-F10-F11 do not work on my laptop.

**Comment by rodmaureirac** [comment]
thanks!

**Comment by ryanamannion** [comment]
I was having issues with my Hotkeys on Ryzen 5 E14 Gen2, and was able to fix them (incl. F9-11) with the fix described here 

https://esc.sh/blog/thinkpad-e-14-fn-key/
