### ISSUE TITLE
Thinkpad E14 Gen 3 (AMD)

### ISSUE THREAD

**Issue by yash-ahir** [rodmaureirac/thinkpad-e14-linux#20]
I haven't been able to find anything relevant to this new model anywhere. I ordered one with the following configuration:

---
- AMD Ryzen 7 5700U Processor (8 Cores / 16 Threads, 1.80 GHz, up to 4.30 GHz, 4 MB Cache L2 / 8 MB Cache L3)
- 16 GB (8 GB Onboard + 8 GB SoDIMM) DDR4 3200MHz
- 1 TB SSD, M.2 2280, PCIe NVMe, TLC
- 35.56cms (14.0) FHD (1920x1080) IPS Anti-glare 300nits Non-Touch Narrow 100% sRGB Display
- Fingerprint Reader
- IR Camera
- Realtek 8822CE 11AC (2x2) & Bluetooth 5.0
- Battery 3 cell, 57Wh

---
I would like to help out with testing Linux when the laptop arrives in approximately 5-6 weeks, cue COVID-19 related shipping delays.

I'll be running Arch Linux on it. I guess that should help with this device since the bleeding edge hardware should be well-complemented by bleeding edge software. I'll also help out testing other distributions. Will update when the laptop arrives.

**Comment by yash-ahir** [comment]
So hey guys, the laptop arrived a few weeks earlier than expected, pleasant enough. Now onto the important stuff.

---
So, as I mentioned before, I'm running Arch Linux on this device. Here's the output of a few commands for some thorough information about the hardware and the software.

**lspci**
```
[yash@thinkpad ~]$ lspci
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Renoir IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe GPP Bridge
00:02.3 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe GPP Bridge
00:02.4 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe GPP Bridge
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 51)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 7
01:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 10)
02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8822CE 802.11ac PCIe Wireless Network Adapter
03:00.0 Non-Volatile memory controller: SK hynix Device 174a
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne (rev c1)
04:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device 1637
04:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
04:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir USB 3.1
04:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir USB 3.1
04:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor (rev 01)
04:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) HD Audio Controller
```

**lsusb**
```
[yash@thinkpad ~]$ lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 0bda:c123 Realtek Semiconductor Corp. Bluetooth Radio
Bus 003 Device 002: ID 04f3:0c4b Elan Microelectronics Corp. ELAN:Fingerprint
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 04f2:b6be Chicony Electronics Co., Ltd Integrated Camera
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**uname -a**
```
[yash@thinkpad ~]$ uname -a
Linux thinkpad 5.13.12-arch1-1 #1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000 x86_64 GNU/Linux
```

**Software**
- Operating System: Arch Linux
- KDE Plasma Version: 5.22.4
- KDE Frameworks Version: 5.85.0
- Qt Version: 5.15.2

---
And now onto the review what does and does not work.

**What works**
- IR Camera (Which needs [this great project](https://github.com/EmixamPP/linux-enable-ir-emitter) to work on this device with [howdy](https://github.com/boltgolt/howdy) for facial authentication).
- All the function keys.
- Suspend to RAM.
- Wi-Fi and Bluetooth (Which I initially doubted since I didn't know that the driver for the Realtek 8822CE available directly in the kernel).
- Speakers.
- Trackpoint and buttons.
- Fans (The machine is super cool, until now it hasn't gotten anything more than a tad bit warm to the touch until I stress tested it with `s-tui` )

**What doesn't work**
- Fingerprint reader (The `04f3:0c3d` from Elan Microelectronics doesn't seem to be supported in [libfprint](https://gitlab.freedesktop.org/libfprint/libfprint/-/issues/214) as of now).

---
Final note:

All-in-all, this is very well rounded device. The thermals are excellent, the performance of the CPU is great and the speakers sound pretty good, they need a tad bit more punch IMO. This turned out of be a much better out-of-the-box experience than I initially expected. Definitely a solid purchase if you're looking for something which is built like a tank and features solid performance to back that up.

**Comment by yash-ahir** [comment]
~~Paging @rodmaureirac in-case they don't notice this.~~

**Comment by rodmaureirac** [comment]
Hi @yash-ahir , thanks for sharing your review on the E14 3rd gen. This weekend I will be writing up the information provided in the repository so that other users can purchase this model knowing that they will be able to install and run Linux properly. this will be the first ryzen laptop documented in the 😄 repo!

**Comment by yash-ahir** [comment]
Glad to help!

**Comment by leezhiwei** [comment]
Just an FYI, been having fedora 34 with 5.13.6 on my E14 Gen 3 for about a week now. Runs flawlessly. Was even able to render some test footage using kdenlive in an acceptable amount of time. Also the wifi card also works well with utilities like airmon-ng and airodump-ng

**Comment by rodmaureirac** [comment]
@yash-ahir Thanks, I will try to do it this weekend

**Comment by ArbitRandomUser** [comment]
@yash-ahir is alt+printscreen + number registering as a keypress ? on my system(archlinux, 5.14.16)  it does not seem to work , i have put it as an issue here https://github.com/rodmaureirac/thinkpad-e14-linux/issues/22#issue-1038146157 , could you confirm the same ?
tried with xev , evtest and showkey no keypress is registered when the number key is pressed with alt and printscreen down, except when the number is 5 or 6.

**Comment by yash-ahir** [comment]
> @yash-ahir is alt+printscreen + number registering as a keypress ? on my system(archlinux, 5.14.16)  it does not seem to work , i have put it as an issue here https://github.com/rodmaureirac/thinkpad-e14-linux/issues/22#issue-1038146157 , could you confirm the same ?
> tried with xev , evtest and showkey no keypress is registered when the number key is pressed with alt and printscreen down, except when the number is 5 or 6.

Yeah I can confirm that Alt + PrtSc + Number doesn't register under either evtest or xev. So I guess this means that not all keyboard events are working as expected, I haven't really tried using this combination before though so at-least it doesn't make the machine un-usable for my use case.

**Comment by ArbitRandomUser** [comment]
@yash-ahir yup , doesnt make the machine un-usable , its a mild inconvenience with new keybindings for my WM  im getting used to though , anyway i think its not a hradware problem it might be a kernel issue since the problem exists even on a USB keyboard plugged into the laptop .
