### ISSUE TITLE
Additional touchpad/keyboard adaptions

### ISSUE THREAD

**Issue by havsar** [rodmaureirac/thinkpad-e14-linux#6]
After the fix for the trackpad and trackpoint issues, I noticed some additional fixes to be made.
Maybe this will help other people aswell.

Issues:
1. Palm detection not working
2. Disable while typing not working

Resolution (Ubuntu, but can be applied to other distros and window managers as well I guess):
1. Create a script on your home folder (touchpad-fixes.sh)
```#! /bin/bash
syndaemon -d -i 0.5 -m 200
synclient PalmDetect=1

```
2. chmod +x the above file
3. Create .desktop file for gnome autostart (~/.config/autostart/touchpad-fixes.desktop):

```[Desktop Entry]
Type=Application
NoDisplay=true
Terminal=false
Name=Libinput Gestures
Exec=~/touchpad-fixes/touchpad-fixes.sh
Comment=Runs a series of commands to apply touchpad fixes (palm detection, disable touchpad while typing)
Categories=System;

```
4. Reboot

Run syndaemon -h to see what the syndaemon i and m params are used for.

**Comment by rodmaureirac** [comment]
According to [Arch Wiki](https://wiki.archlinux.org/index.php/Touchpad_Synaptics#Using_syndaemon) syndaemon requires synaptics, however most distros are using libinput instead. I don't know if is a good idea to replace libinput (specially when you are running GNOME).

Anyways, you can install synaptics by typing:
- Fedora: dnf install xorg-x11-drv-synaptics-legacy
- Ubuntu: apt-get install xserver-xorg-input-synaptics
- Arch: pacman -S xf86-input-synaptics

**Comment by havsar** [comment]
@rodmaureirac Maybe you are right. I still feel like something is fishy with my touchpad drivers. It feels kind of weird sometimes.
So I should not be using Synaptics at all on Ubuntu? 

My xinput:
Device 'ETPS/2 Elantech Touchpad':
	Device Enabled (179):	1
	Coordinate Transformation Matrix (181):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	Device Accel Profile (310):	1
	Device Accel Constant Deceleration (311):	2.500000
	Device Accel Adaptive Deceleration (312):	1.000000
	Device Accel Velocity Scaling (313):	12.500000
	Synaptics Edges (314):	122, 2938, 90, 1579
	Synaptics Finger (315):	1, 1, 0
	Synaptics Tap Time (316):	180
	Synaptics Tap Move (317):	153
	Synaptics Tap Durations (318):	180, 180, 100
	Synaptics ClickPad (319):	1
	Synaptics Middle Button Timeout (320):	0
	Synaptics Two-Finger Pressure (321):	282
	Synaptics Two-Finger Width (322):	7
	Synaptics Scrolling Distance (323):	-69, 69
	Synaptics Edge Scrolling (324):	0, 0, 0
	Synaptics Two-Finger Scrolling (325):	1, 1
	Synaptics Move Speed (326):	1.000000, 1.750000, 0.057389, 0.000000
	Synaptics Off (327):	0
	Synaptics Locked Drags (328):	0
	Synaptics Locked Drags Timeout (329):	5000
	Synaptics Tap Action (330):	0, 0, 0, 0, 1, 3, 2
	Synaptics Click Action (331):	1, 3, 2
	Synaptics Circular Scrolling (332):	0
	Synaptics Circular Scrolling Distance (333):	0.100000
	Synaptics Circular Scrolling Trigger (334):	0
	Synaptics Circular Pad (335):	0
	Synaptics Palm Detection (336):	0
	Synaptics Palm Dimensions (337):	10, 200
	Synaptics Coasting Speed (338):	20.000000, 50.000000
	Synaptics Pressure Motion (339):	30, 160
	Synaptics Pressure Motion Factor (340):	1.000000, 1.000000
	Synaptics Resolution Detect (341):	1
	Synaptics Grab Event Device (342):	0
	Synaptics Gestures (343):	1
	Synaptics Capabilities (344):	1, 0, 0, 1, 1, 1, 1
	Synaptics Pad Resolution (345):	31, 31
	Synaptics Area (346):	0, 0, 0, 0
	Synaptics Soft Button Areas (347):	0, 0, 0, 0, 0, 0, 0, 0
	Synaptics Noise Cancellation (348):	17, 17
	Device Product ID (305):	2, 14
	Device Node (304):	"/dev/input/event5"

**Comment by rodmaureirac** [comment]
Ok, so ive tried synaptics on my thinkpad. touchpad feels way more imprecise and im not able to change the speed and the scroll direction on gnome. ive also tried it on xfce and it seems to be working except for chrome and some others electron apps (like discord, teams, atom, etc). For some reason they ignore the touchpad configuration. definitely not recommended (at least on fedora)

**Comment by havsar** [comment]
@rodmaureirac I just switched completely to libinput and it feels much better.

```
sudo apt-get remove --purge --auto-remove  xserver-xorg-input-synaptics
reboot -n
```

Fixed all the problems.
You can close this issue :)
